#:schema https://developers.openai.com/codex/config-schema.json

model_verbosity = "low"
model = "gpt-6-astra"
model_reasoning_effort = "low"
plan_mode_reasoning_effort = "low"

[agents]
enabled = false
