begin;

set local statement_timeout = '10min';
set local lock_timeout = '5s';
set local synchronous_commit = off;

create temporary table task11_preview_context on commit drop as
select
  supplied.run_id,
  'ct11p:' || md5(supplied.run_id) as namespace,
  'task11preview' || substr(md5(supplied.run_id), 1, 16) as attempt_prefix,
  statement_timestamp() as observed_at
from (select __TASK11_PREVIEW_RUN_ID__::text as run_id) as supplied;

alter table task11_preview_context
  add column attempt_id_prefix text;

update task11_preview_context
   set attempt_id_prefix = 'ctpa_' || attempt_prefix || '_';

create temporary table task11_preview_owners on commit drop as
select
  owner.owner_number,
  md5(context.run_id || ':owner:' || owner.owner_number::text)::uuid as owner_user_id,
  context.namespace || ':storage-session:' || owner.owner_number::text as session_reference_id,
  md5(context.run_id || ':billing-period:' || owner.owner_number::text)::uuid as billing_period_id,
  statement_timestamp() - interval '1 day' as period_start,
  statement_timestamp() + interval '29 days' as period_end
from task11_preview_context as context
cross join generate_series(1, 20) as owner(owner_number);

-- Preview storage evidence is isolated in temporary relations so rollback does
-- not leave bloat or index pages in the shared Preview schema.
create temporary table task11_preview_storage_billing_period_usage (
  id uuid primary key,
  owner_user_id uuid not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  period_state text not null
) on commit drop;

create temporary table task11_preview_storage_logical_attempts (
  attempt_id text primary key,
  owner_user_id uuid not null,
  billing_period_usage_id uuid not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  input_characters bigint not null,
  logical_state text not null,
  committed_input_characters bigint not null,
  expires_at timestamptz not null
) on commit drop;

create index task11_preview_storage_logical_owner_expiry_idx
  on task11_preview_storage_logical_attempts (owner_user_id, expires_at);

create temporary table task11_preview_storage_attempt_receipts (
  id bigint generated by default as identity primary key,
  attempt_id text not null,
  provider_attempt text not null,
  provider_kind text not null,
  session_reference_id text not null,
  owner_user_id uuid not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  utc_month date not null,
  attempt_state text not null,
  expires_at timestamptz not null,
  requested_input_characters bigint not null,
  requested_cost_micros bigint not null,
  requested_request_count integer not null,
  requested_token_count bigint not null,
  billing_period_usage_id uuid not null,
  committed_input_characters bigint not null,
  unique (attempt_id, provider_attempt)
) on commit drop;

create index task11_preview_storage_receipt_owner_expiry_idx
  on task11_preview_storage_attempt_receipts (owner_user_id, expires_at);

create temporary table task11_preview_storage_provider_detail_source_receipts (
  attempt_id text not null,
  provider_attempt text not null,
  expires_at timestamptz not null,
  primary key (attempt_id, provider_attempt)
) on commit drop;

create temporary table task11_preview_storage_provider_hourly_details (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null,
  provider text not null,
  utc_hour timestamptz not null,
  request_count integer not null,
  session_count integer not null,
  comment_count integer not null,
  input_characters bigint not null,
  output_characters bigint not null,
  input_tokens bigint not null,
  output_tokens bigint not null,
  estimated_cost_micros bigint not null,
  success_count integer not null,
  failure_count integer not null,
  latency_101_to_250_ms_count integer not null,
  unique (owner_user_id, provider, utc_hour)
) on commit drop;

create index task11_preview_storage_hourly_owner_hour_idx
  on task11_preview_storage_provider_hourly_details (owner_user_id, utc_hour);

create temporary table task11_preview_storage_session_summaries (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null,
  session_reference_id text not null unique,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  stop_reason text not null,
  provider_request_count integer not null,
  translated_message_count integer not null,
  input_characters bigint not null,
  output_characters bigint not null
) on commit drop;

insert into task11_preview_storage_billing_period_usage (
  id, owner_user_id, period_start, period_end, period_state
)
select billing_period_id, owner_user_id, period_start, period_end, 'open'
  from task11_preview_owners;

create temporary table task11_preview_storage_provider_source_plan on commit drop as
select
  provider_source.source_number,
  context.attempt_id_prefix || substr(
    md5(context.run_id || ':storage-attempt:' || provider_source.source_number::text)
    || md5(context.run_id || ':storage-attempt-suffix:' || provider_source.source_number::text),
    1,
    43
  ) as attempt_id,
  context.namespace || ':storage-provider:' || provider_source.source_number::text as provider_attempt,
  run_owner.owner_number,
  run_owner.owner_user_id,
  run_owner.billing_period_id,
  run_owner.period_start,
  run_owner.period_end,
  case
    when (((provider_source.source_number - 1) / 20) % 2) = 0 then 'openai_attempt'
    else 'azure_direct_fallback'
  end as provider_kind,
  case
    when (((provider_source.source_number - 1) / 20) % 2) = 0 then 'openai'
    else 'azure_fallback'
  end as provider,
  date_trunc('hour', statement_timestamp())
    - (((provider_source.source_number - 1) / 40)::integer * interval '1 hour') as utc_hour
from task11_preview_context as context
cross join generate_series(1, 28800) as provider_source(source_number)
join task11_preview_owners as run_owner
  on run_owner.owner_number = ((provider_source.source_number - 1) % 20) + 1;

insert into task11_preview_storage_logical_attempts (
  attempt_id,
  owner_user_id,
  billing_period_usage_id,
  period_start,
  period_end,
  input_characters,
  logical_state,
  committed_input_characters,
  expires_at
)
select
  context.attempt_id_prefix || substr(
    md5(context.run_id || ':storage-attempt:' || logical_attempt.attempt_number::text)
    || md5(context.run_id || ':storage-attempt-suffix:' || logical_attempt.attempt_number::text),
    1,
    43
  ),
  run_owner.owner_user_id,
  run_owner.billing_period_id,
  run_owner.period_start,
  run_owner.period_end,
  100,
  'committed',
  100,
  statement_timestamp() + interval '27 hours'
from task11_preview_context as context
cross join generate_series(1, 129600) as logical_attempt(attempt_number)
join task11_preview_owners as run_owner
  on run_owner.owner_number = ((logical_attempt.attempt_number - 1) % 20) + 1;

insert into task11_preview_storage_attempt_receipts (
  attempt_id,
  provider_attempt,
  provider_kind,
  session_reference_id,
  owner_user_id,
  period_start,
  period_end,
  utc_month,
  attempt_state,
  expires_at,
  requested_input_characters,
  requested_cost_micros,
  requested_request_count,
  requested_token_count,
  billing_period_usage_id,
  committed_input_characters
)
select
  context.attempt_id_prefix || substr(
    md5(context.run_id || ':storage-attempt:' || receipt.receipt_number::text)
    || md5(context.run_id || ':storage-attempt-suffix:' || receipt.receipt_number::text),
    1,
    43
  ),
  coalesce(provider_source.provider_attempt, context.namespace || ':storage-provider:' || receipt.receipt_number::text),
  coalesce(provider_source.provider_kind,
    case when receipt.receipt_number % 2 = 0 then 'openai_attempt' else 'azure_direct_fallback' end),
  context.namespace || ':storage-session:' || (((receipt.receipt_number - 1) % 14400) + 1)::text,
  run_owner.owner_user_id,
  run_owner.period_start,
  run_owner.period_end,
  date_trunc('month', statement_timestamp() at time zone 'UTC')::date,
  'committed',
  statement_timestamp() + interval '27 hours',
  100,
  50,
  1,
  30,
  run_owner.billing_period_id,
  100
from task11_preview_context as context
cross join generate_series(1, 129600) as receipt(receipt_number)
join task11_preview_owners as run_owner
  on run_owner.owner_number = ((receipt.receipt_number - 1) % 20) + 1
left join task11_preview_storage_provider_source_plan as provider_source
  on provider_source.source_number = receipt.receipt_number;

insert into task11_preview_storage_provider_detail_source_receipts (
  attempt_id,
  provider_attempt,
  expires_at
)
select attempt_id, provider_attempt, statement_timestamp() + interval '27 hours'
  from task11_preview_storage_provider_source_plan;

insert into task11_preview_storage_provider_hourly_details (
  owner_user_id,
  provider,
  utc_hour,
  request_count,
  session_count,
  comment_count,
  input_characters,
  output_characters,
  input_tokens,
  output_tokens,
  estimated_cost_micros,
  success_count,
  failure_count,
  latency_101_to_250_ms_count
)
select
  provider_source.owner_user_id,
  provider_source.provider,
  provider_source.utc_hour,
  60,
  1,
  60,
  6000,
  5400,
  1800,
  1500,
  3000,
  59,
  1,
  60
from task11_preview_storage_provider_source_plan as provider_source;

insert into task11_preview_storage_session_summaries (
  owner_user_id,
  session_reference_id,
  started_at,
  ended_at,
  stop_reason,
  provider_request_count,
  translated_message_count,
  input_characters,
  output_characters
)
select
  run_owner.owner_user_id,
  context.namespace || ':storage-session:' || summary.summary_number::text,
  statement_timestamp()
    - ((summary.summary_number - 1)::double precision / 14399.0) * interval '90 days'
    - interval '3 hours',
  statement_timestamp()
    - ((summary.summary_number - 1)::double precision / 14399.0) * interval '90 days',
  'session-time-limit',
  180,
  180,
  18000,
  16200
from task11_preview_context as context
cross join generate_series(1, 14400) as summary(summary_number)
join task11_preview_owners as run_owner
  on run_owner.owner_number = ((summary.summary_number - 1) % 20) + 1;

analyze task11_preview_storage_attempt_receipts;
analyze task11_preview_storage_logical_attempts;
analyze task11_preview_storage_provider_detail_source_receipts;
analyze task11_preview_storage_billing_period_usage;
analyze task11_preview_storage_provider_hourly_details;
analyze task11_preview_storage_session_summaries;

do $$
declare
  context_row record;
  logical_count bigint;
  receipt_count bigint;
  source_count bigint;
  hourly_count bigint;
  summary_count bigint;
begin
  select * into context_row from task11_preview_context;
  select count(*) into logical_count from task11_preview_storage_logical_attempts;
  select count(*) into receipt_count from task11_preview_storage_attempt_receipts;
  select count(*) into source_count from task11_preview_storage_provider_detail_source_receipts;
  select count(*) into hourly_count from task11_preview_storage_provider_hourly_details;
  select count(*) into summary_count from task11_preview_storage_session_summaries;

  if logical_count <> 129600
    or receipt_count <> 129600
    or source_count <> 28800
    or hourly_count <> 28800
    or summary_count <> 14400
    or exists (
      select logical_attempt.attempt_id
        from task11_preview_storage_logical_attempts as logical_attempt
        left join task11_preview_storage_attempt_receipts as attempt_receipt
          on attempt_receipt.attempt_id = logical_attempt.attempt_id
       group by logical_attempt.attempt_id
      having count(attempt_receipt.id) <> 1
    )
    or (
      select count(*)
        from task11_preview_storage_provider_source_plan as provider_source
        join task11_preview_storage_provider_detail_source_receipts as source_receipt
          on source_receipt.attempt_id = provider_source.attempt_id
         and source_receipt.provider_attempt = provider_source.provider_attempt
        join task11_preview_storage_provider_hourly_details as provider_hourly_details
          on provider_hourly_details.owner_user_id = provider_source.owner_user_id
         and provider_hourly_details.provider = provider_source.provider
         and provider_hourly_details.utc_hour = provider_source.utc_hour
    ) <> 28800
    or exists (
      select 1
        from task11_preview_storage_session_summaries as summary
       where summary.started_at > summary.ended_at
          or summary.ended_at > statement_timestamp()
          or summary.ended_at < statement_timestamp() - interval '90 days' - interval '1 second'
    )
  then
    raise exception 'Task 11 Preview storage fixture row cardinality or retention shape is not exact';
  end if;
end;
$$;

-- This is a temporary-relation observation, not Dashboard quota evidence.
create temporary table task11_storage_measurement on commit drop as
select
  coalesce(sum(pg_total_relation_size(class.oid)), 0)::bigint as paid_relation_total_bytes,
  coalesce(sum(pg_indexes_size(class.oid)), 0)::bigint as paid_relation_index_bytes
from pg_class as class
join pg_namespace as namespace on namespace.oid = class.relnamespace
where namespace.nspname like 'pg_temp_%'
  and class.relkind in ('r', 'p')
  and class.relname like 'task11_preview_storage_%';

create temporary table task11_storage_metrics on commit drop as
select
  (select count(*) from task11_preview_storage_logical_attempts)::bigint as logical_attempt_rows,
  (select count(*) from task11_preview_storage_attempt_receipts)::bigint as attempt_receipt_rows,
  (select count(*) from task11_preview_storage_provider_detail_source_receipts)::bigint as provider_source_receipt_rows,
  (select count(*) from task11_preview_storage_provider_hourly_details)::bigint as provider_hourly_rows,
  (select count(*) from task11_preview_storage_session_summaries)::bigint as session_summary_rows,
  measurement.paid_relation_total_bytes,
  measurement.paid_relation_index_bytes
from task11_storage_measurement as measurement;

drop table task11_preview_storage_session_summaries;
drop table task11_preview_storage_provider_hourly_details;
drop table task11_preview_storage_provider_detail_source_receipts;
drop table task11_preview_storage_attempt_receipts;
drop table task11_preview_storage_logical_attempts;
drop table task11_preview_storage_billing_period_usage;
drop table task11_preview_storage_provider_source_plan;

create temporary table task11_storage_cleanup_status on commit drop as
select count(*)::bigint as remaining_rows
from pg_class as class
join pg_namespace as namespace on namespace.oid = class.relnamespace
where namespace.nspname like 'pg_temp_%'
  and class.relkind in ('r', 'p')
  and class.relname like 'task11_preview_storage_%';

do $$
begin
  if (select remaining_rows from task11_storage_cleanup_status) <> 0 then
    raise exception 'Task 11 Preview temporary storage cleanup left rows';
  end if;
end;
$$;

select jsonb_build_object(
  'marker', 'TASK11_PREVIEW_RESULT',
  'fixture', 'storage',
  'logical_attempt_rows', metrics.logical_attempt_rows,
  'attempt_receipt_rows', metrics.attempt_receipt_rows,
  'provider_source_receipt_rows', metrics.provider_source_receipt_rows,
  'provider_hourly_rows', metrics.provider_hourly_rows,
  'session_summary_rows', metrics.session_summary_rows,
  'paid_relation_total_bytes', metrics.paid_relation_total_bytes,
  'paid_relation_index_bytes', metrics.paid_relation_index_bytes,
  'cleanup_rows_remaining', cleanup_status.remaining_rows,
  'measurement_scope', 'temporary-relation-transaction-only',
  'dashboard_quota_evidence', 'UNKNOWN',
  'external_egress', 'UNKNOWN',
  'external_realtime', 'UNKNOWN'
) as task11_preview_result
from task11_storage_metrics as metrics
cross join task11_storage_cleanup_status as cleanup_status;

rollback;
