import fs from 'node:fs';
import {guard,cli,check,json,save,ROOT,CONTROL,config,workerName,sha} from './common.mjs';
const stage=process.argv[2],a=guard({closure:stage==='close'});check(['existing','secrets','live','close'].includes(stage));
if(stage==='existing'){check(!fs.existsSync(ROOT+'/runtime'));const p=json(CONTROL+'/billing-reviewed.json').find(x=>x.service==='cloudflare');check(p.free===true&&p.priceUSD===0&&json(ROOT+'/control/allocation-claimed.json').allocatedAt-p.capturedAt<=1800000);}else if(stage==='secrets')check(json(CONTROL+'/initial-secrets-result.json').exitCode===0);else check(json(CONTROL+'/deploy-'+stage+'-result.json').status==='DEPLOYED_VERSION_RECORDED');
save('version-'+stage+'-claimed.json',{at:Date.now(),stage,reads:2});
const list=cli(['deployments','list','--json','--config',config]);check(list.status===0,'DEPLOYMENTS_READ_FAILED');const values=JSON.parse(list.stdout);check(Array.isArray(values)&&values.length>0);const latest=values.sort((a,b)=>a.created_on.localeCompare(b.created_on)).at(-1);check(latest.versions?.length===1&&latest.versions[0].percentage===100);const version=latest.versions[0].version_id;if(stage==='existing')check(version===json(ROOT+'/existing-worker-baseline.json').version,'EXISTING_VERSION_CHANGED');else if(stage!=='secrets')check(version===json(CONTROL+'/deploy-'+stage+'-result.json').version,'ACTIVE_VERSION_MISMATCH');
const detail=cli(['versions','view',version,'--json','--config',config]);check(detail.status===0,'VERSION_READ_FAILED');const value=JSON.parse(detail.stdout),bindings=value.resources?.bindings??[];check(value.id===version);
const expected=stage==='existing'?['CONTROLLER_MODE','CONTROLLER_POLICY_JSON','GUARDIAN']:['CONTROLLER_MODE','CONTROLLER_OPERATOR_TOKEN','CONTROLLER_POLICY_JSON',...(json(ROOT+'/fresh/verification.json').special?['CONTROLLER_SAFE_CLOSURE_GRANT_JSON']:[]),'GUARDIAN','SUPABASE_SCOPED_TOKEN'];check(JSON.stringify(bindings.map(b=>b.name).sort())===JSON.stringify(expected));const mode=bindings.find(b=>b.name==='CONTROLLER_MODE');check(mode.type==='plain_text'&&mode.text===(stage==='live'?'live':'disabled'));
const secrets=bindings.filter(b=>b.type==='secret_text');check(secrets.length===(stage==='existing'?1:json(CONTROL+'/initial-secrets-result.json').names.length));const guardian=bindings.find(b=>b.name==='GUARDIAN');check(guardian.type==='durable_object_namespace'&&guardian.class_name==='Gate1RecoveryController'&&typeof guardian.namespace_id==='string');const namespaceSha256=sha(guardian.namespace_id);check(namespaceSha256===json(ROOT+'/existing-worker-baseline.json').namespaceSha256,'NAMESPACE_CHANGED');
const receipt={at:Date.now(),stage,version,activeVersionConfirmed:true,trafficPercentage:100,mode:mode.text,encryptedSecrets:secrets.length,namespaceSha256,namespacePreserved:true,source:'CLOUDFLARE_DEPLOYMENTS_AND_VERSION_API'};save('version-'+stage+'.json',receipt);
if(stage==='live'){const grant=json(ROOT+'/fresh/verification.json');fs.writeFileSync(ROOT+'/deployment-receipt.json',JSON.stringify({...receipt,sourceCommit:a.sourceCommit,bundleSha256:a.manifest.controllerBundleSha256,policySha256:sha(JSON.stringify(a.policy)),grantSha256:grant.grantSha256,executionManifestSha256:grant.manifestSha256,workerName,origin:a.manifest.controllerOrigin})+'\n',{flag:'wx'});}
console.log(JSON.stringify(receipt));
